theme: jekyll-theme-minimal
title: Linus Carrier's Portfolio
description: My name is Linus Carrier, I am a undergraduate student at Lehigh University pursuing majors in journalism and economics. I am from Darien, Connecticut and I have 2 older sisters and a dog. 
https://www.linkedin.com/in/linus-carrier-0b0b2b1a2/
